Updated k8s version support for tanzu
dell/csi-unity pull request #136
Opened 2023-03-01 11:40 UTC by karthikk92

# Description
Updated k8s version support for Tanzu

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/583 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

2023-03-01 11:43 UTC, bandak2 approved these changes

2023-03-01 11:44 UTC, rensyct requested changes

2023-03-01 11:44 UTC, rensyct commented on helm/csi-unity/templates/_helpers.tpl
> +      {{- print "k8s.gcr.io/sig-storage/csi-attacher:v4.0.0" -}}
@karthikk92 , why are all the sidecar version changes reverted. Same comment for all the modified lines in this file

2023-03-01 11:53 UTC, karthikk92 commented on helm/csi-unity/templates/_helpers.tpl
> +      {{- print "k8s.gcr.io/sig-storage/csi-attacher:v4.0.0" -}}
taken care

2023-03-01 12:29 UTC, rensyct commented
@karthikk92 , please sign all your commits

2023-03-01 12:36 UTC, karthikk92 commented
> @karthikk92 , please sign all your commits

Taken care

2023-03-02 05:19 UTC, rensyct approved these changes

2023-03-02 05:20 UTC, panigs7 approved these changes

2023-03-02 05:21 UTC, merged