Remove possible nil pointer dereference in mkdir
dell/csi-unity pull request #172
Opened 2023-10-13 13:42 UTC by cbartoszDell

# Description
There was a possibility for nil pointer dereference on `os.Stat` result. This is now fixed.

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
I have crated test cases for all but one path in the function, because I haven't found a way to trigger `fs` errors other than `fs.ErrNotFound` easily. The logic is pretty simple so it should be correct.

2023-10-18 08:52 UTC, adarsh-dell commented on service/mount.go
> +) (bool, error) {
Is this a typo or did a linter warning occur? I'm having trouble understanding why the comma was introduced here.

2023-10-18 08:54 UTC, adarsh-dell commented
Hi @cbartoszDell Can we update the License: Copyright © 2019 - **_2023_** for all files that we are trying to modify?

2023-10-18 09:14 UTC, adarsh-dell commented on service/mount.go
> +	if err := os.MkdirAll(path, 0o750); err != nil {
I think we will reach the return statement on line 742 if the directory doesn't exist. So, is this code segment ever executed?

2023-10-18 10:18 UTC, adamginna-dell approved these changes

2023-10-20 07:47 UTC, cbartoszDell commented on service/mount.go
> +) (bool, error) {
It's one of the linters from golangci-lint package that puts return types on separate line in case of long parameter lists I think. The comma is necessary.

2023-10-20 07:51 UTC, adarsh-dell submitted a review, later dismissed
LGTM, considering copyright years will get modified as part of a separate PR.

2023-10-31 10:01 UTC, rajendraindukuri approved these changes

2023-10-31 17:03 UTC, gallacher requested changes
Is this code change fixing a defect? Please associate it with a GitHub issue.  Thanks.

2023-11-07 17:38 UTC, gallacher approved these changes

2023-11-07 17:41 UTC, merged