Add NFS support for PVC metrics in controller
dell/csi-unity pull request #30
Opened 2021-11-15 12:35 UTC by rensyct

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| dell/csm#94 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- Ensured that controller logs provides health state of the filesystem
- Ensured that node logs provides health state of the filesystem along with volume stats

2021-11-15 13:56 UTC, ashish2207 requested changes

2021-11-15 13:56 UTC, ashish2207 commented on service/controller.go
> +				if err == gounity.FilesystemNotFoundError {
should check for snapshotnotfound error in case of findsnapshot error

2021-11-15 14:11 UTC, ashish2207 requested changes

2021-11-15 14:11 UTC, ashish2207 commented on service/controller.go
> +				return nil, status.Error(codes.NotFound, utils.GetMessageWithRunID(rid, "Find filesystem: %s failed with error: %v", volID, err))
if abnormal is set to true, this return should not happen

2021-11-15 14:11 UTC, ashish2207 commented on service/controller.go
> +			filesystem, err = s.getFilesystemByResourceID(ctx, snapResp.SnapshotContent.StorageResource.Id, arrayID)
should be skipped if abnormal is true

2021-11-15 14:11 UTC, ashish2207 commented on service/controller.go
> +		for _, nfsShare := range filesystem.FileContent.NFSShare {
should be skipped if abnormal true

2021-11-15 14:11 UTC, ashish2207 commented on service/controller.go
> +		if filesystem.FileContent.Health.Value != 5 {
should be skipped if abnormal true

2021-11-15 14:14 UTC, ashish2207 requested changes

2021-11-15 14:14 UTC, ashish2207 commented on service/controller.go
> +				abnormal = true
if pvc not found as filesystem then we will set abnormal as true, but if it is found as snapshot, at line 1826, then we should not say abnormal true

2021-11-15 14:55 UTC, rensyct commented on service/controller.go
> +				if err == gounity.FilesystemNotFoundError {
done

2021-11-15 15:22 UTC, gallacher requested changes
I do not see any unit tests new/updated to test the code that has been added here.  Please add those to this PR.

2021-11-16 06:22 UTC, rensyct commented on service/controller.go
> +				return nil, status.Error(codes.NotFound, utils.GetMessageWithRunID(rid, "Find filesystem: %s failed with error: %v", volID, err))
done

2021-11-16 06:22 UTC, rensyct commented on service/controller.go
> +			filesystem, err = s.getFilesystemByResourceID(ctx, snapResp.SnapshotContent.StorageResource.Id, arrayID)
done

2021-11-16 06:22 UTC, rensyct commented on service/controller.go
> +		for _, nfsShare := range filesystem.FileContent.NFSShare {
done

2021-11-16 06:22 UTC, rensyct commented on service/controller.go
> +		if filesystem.FileContent.Health.Value != 5 {
done

2021-11-16 06:26 UTC, rensyct commented on service/controller.go
> +				abnormal = true
done

2021-11-16 08:35 UTC, francis-nijay submitted a review, later dismissed

2021-11-16 09:09 UTC, ashish2207 approved these changes

2021-11-16 09:25 UTC, prasar6 submitted a review, later dismissed

2021-11-16 09:44 UTC, francis-nijay submitted a review, later dismissed

2021-11-16 14:51 UTC, gallacher approved these changes
Thank you for adding unit tests

2021-11-16 15:22 UTC, prasar6 approved these changes

2021-11-16 15:36 UTC, merged