KRV-2548 : Unity CSI node driver reports "invalid memory address or nil pointer dereference
dell/csi-unity pull request #55
Opened 2022-01-12 11:56 UTC by karthikk92

# Description
Unity CSI node driver reports "invalid memory address or nil pointer dereference

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/152 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
1. building image after code change : 
<img width="747" alt="building_image" src="https://user-images.githubusercontent.com/92289639/149135829-81782702-678a-40fb-8816-6ee8127d26f9.PNG">

2. values.yaml file: 

<img width="476" alt="myvalues yaml" src="https://user-images.githubusercontent.com/92289639/149135917-ab5f4e50-a943-4292-ba87-84d23e05dc7d.PNG">

3. After installation:
<img width="528" alt="after installation" src="https://user-images.githubusercontent.com/92289639/149135973-665639e4-4183-4dbd-8ebc-8ad590ec6935.PNG">

2022-01-12 12:57 UTC, rensyct requested changes
Please fix the format and lint issues

2022-01-12 13:55 UTC, karthikk92 commented
> Please fix the format and lint issues

taken care

2022-01-13 05:17 UTC, rensyct commented on service/node.go
> +			return status.Error(codes.Internal, utils.GetMessageWithRunID(rid, "Unable to find  tenant Name : %s", tenantName))
Since the REST API fetches all tenants, we can change the message to "Unable to fetch tenants". We dont have to pass the tenant name in this comment as we are not passing that in the REST API call

2022-01-13 05:36 UTC, karthikk92 commented on service/node.go
> +			return status.Error(codes.Internal, utils.GetMessageWithRunID(rid, "Unable to find  tenant Name : %s", tenantName))
tc

2022-01-13 11:33 UTC, rensyct submitted a review, later dismissed

2022-01-17 07:58 UTC, panigs7 submitted a review, later dismissed

2022-01-18 05:19 UTC, panigs7 approved these changes

2022-01-18 06:10 UTC, rensyct approved these changes

2022-01-18 07:05 UTC, merged