Update verify script to validate min and max versions supported for Openshift
dell/csi-unity pull request #87
Opened 2022-05-16 08:11 UTC by rajendraindukuri

# Description
As part of OCP 4.10 support for csi-unity driver , fixed verify script which validates MIN and MAX versions of Openshift supported by the driver

# GitHub Issues

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/305 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Tested helm installation checks for positive and negative scenarios in OCP 4.10 env. Please find below screenshots for reference:

![Min_version_check_410](https://user-images.githubusercontent.com/82365588/168547964-fe2f9e0e-a68c-473a-b19b-bb20864a0460.JPG)

![max_version_check](https://user-images.githubusercontent.com/82365588/168548025-234b1f8e-221b-4846-8335-5f1dfe17ec63.JPG)

2022-05-16 12:14 UTC, francis-nijay approved these changes

2022-05-16 12:22 UTC, prablr79 commented on dell-csi-helm-installer/verify-csi-unity.sh
> +  verify_openshift_versions "4.9" "4.10"
why are we removing 4.8 EUS support ? is that discussed in PO meeting ?

2022-05-16 12:23 UTC, prablr79 requested changes

2022-05-16 12:23 UTC, prablr79 commented on dell-csi-helm-installer/verify.sh
> +  if (( ${V%%.*} < ${MIN%%.*} || ( ${V%%.*} == ${MIN%%.*} && ${V##*.} < ${MIN##*.} ) )) ; then
is this change applicable across drivers ?

2022-05-17 05:20 UTC, rajendraindukuri commented on dell-csi-helm-installer/verify-csi-unity.sh
> +  verify_openshift_versions "4.9" "4.10"
Hi @prablr79 , these are just inputs for Major and Minor versions. We don't validate for EUS versions as it is implicitly covered.

2022-05-17 05:25 UTC, rajendraindukuri commented on dell-csi-helm-installer/verify.sh
> +  if (( ${V%%.*} < ${MIN%%.*} || ( ${V%%.*} == ${MIN%%.*} && ${V##*.} < ${MIN##*.} ) )) ; then
Yes @prablr79 . Thanks for bringing this up. I will raise a common PR for all drivers.

2022-05-17 06:23 UTC, prablr79 commented on dell-csi-helm-installer/verify-csi-unity.sh
> +  verify_openshift_versions "4.9" "4.10"
ok thanks

2022-05-17 06:23 UTC, prablr79 approved these changes
lgtm with another PR for across drivers to cover.

2022-05-17 12:47 UTC, rajendraindukuri commented on dell-csi-helm-installer/verify-csi-unity.sh
> +  verify_openshift_versions "4.9" "4.10"
Hi @prablr79 Raised PR s for all drivers repos except for powerstore as some of the other validations are getting overridden.. Passed on the info to team

2022-05-17 14:17 UTC, rensyct approved these changes

2022-05-17 14:50 UTC, merged